### ISSUE TITLE
requirement.txt missing

### ISSUE THREAD

**Issue by jliellen** [snap-stanford/roland#1]
Hi there,  `install.sh` has one command line of installing all the dependencies, but I didn't find requirement.txt anywhere.
Also, I found it a bit unclear how to run a roland example step by step. I'm guessing the following? 

1. `bash get_roland_public_data.sh`
2. `bash install.sh`
3. `python3 setup.py develop` (as I see this in graphgym)
4. Then I can go to `run` and `bash run_single_roland.sh`

Could you please help with it? Thanks in advance!

**Comment by TianyuDu** [comment]
My apologies for the missing requirement file

Since this project is built upon Graphgym directly, these two projects share the `requirements.txt` file. You can use the requirement file from [Graphgym](https://github.com/snap-stanford/GraphGym) directly. I have also added a `requirements.txt` file to this repo. as well.

Alternatively, you might want to use the `yaml` file [here](https://github.com/snap-stanford/roland/blob/master/roland_environment.yml) to create a conda environment for replication.

Thanks!

**Comment by lwhere** [comment]
You could also add "dask-ml" in the requirment.txt, which is what I got the error warning when I ran the code in colab.
